language: node_js

node_js:
  - lts/*

script:
  - ls -ila
  - npm run dev
  - ls -ila

deploy:
  provider: pages
  skip-cleanup: true
  # local_dir: ./dist
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  target_branch: gh-pages
  commit_message: "Deploy %{git_commit_msg}"
  edge: true # opt in to dpl v2